name: debezium
services:
  master:
    image: mysql:8.0
    volumes:
      - type: bind
        source: ./master/master.conf
        target: /etc/mysql/conf.d/master.cnf
      - type: bind
        source: ./master/login.conf
        target: /root/.my.cnf
      - type: bind
        source: ./master/scripts
        target: /opt/scripts
      - type: volume
        source: mysql_master
        target: /var/lib/mysql
    ports:
      - 13306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
  slave:
    image: mysql:8.0
    volumes:
      - type: bind
        source: ./slave/slave.conf
        target: /etc/mysql/conf.d/slave.cnf
      - type: bind
        source: ./slave/login.conf
        target: /root/.my.cnf
      - type: bind
        source: ./slave/scripts
        target: /opt/scripts
      - type: volume
        source: mysql_slave
        target: /var/lib/mysql
    ports:
      - 23306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      SERVER_ID: 1
    healthcheck:
      test: /zookeeper/bin/zkServer.sh print-cmd || exit 1
      timeout: 10s
      retries: 10
  kafka:
    image: quay.io/debezium/kafka:2.3
    ports:
      - 9092:9092
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      NODE_ID: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: /kafka/bin/kafka-topics.sh --list --bootstrap-server kafka:9092 || exit 1
      timeout: 10s
      retries: 10
  connect:
    image: quay.io/debezium/connect:2.3
    volumes:
      - type: volume
        source: connect_conf
        target: /kafka/config
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      master:
        condition: service_healthy
      slave:
        condition: service_healthy
    healthcheck:
      test: curl -s -o /dev/null -w "%{http_code}" http://connect:8083/connectors || exit 1
      timeout: 10s
      retries: 10
volumes:
  mysql_master:
  mysql_slave:
